# Copyright 2025 Google LLC. This software is provided as-is, without warranty
# or representation for any use or purpose. Your use of it is subject to
# your agreement with Google.

PROJECT_ID: kr-ais-demo
REGION: us-central1
FLASH_MODELS: 
  - gemini-2.0-flash-001
IMAGEN3_EDIT_MODELS:
  - imagen-3.0-capability-001
SAFETY_FILTER_LEVELS:
  - BLOCK_LOW_AND_ABOVE
  - BLOCK_MEDIUM_AND_ABOVE
  - BLOCK_ONLY_HIGH
  - BLOCK_NONE
PERSON_GENERATION_MODES:
  - ALLOW_ADULT
  - ALLOW_ALL
  - DONT_ALLOW
AUTO_MASK_MODES:
  - MASK_MODE_FOREGROUND
  - MASK_MODE_BACKGROUND
IMAGEN3_GENERATION_MODELS: 
  - imagen-3.0-generate-002
VEO_MODELS: 
  - veo-2.0-generate-001
VEO_PERSON_GENERATION_MODES:
  - allow_adult
  - disallow
VEO_ASPECT_RATIOS:
  - "16:9"
  - "9:16"
IMAGEN_MODELS:
  - imagen-3.0-generate-002