cloudfunctionsV1RequireIngressInternalAndLoadBalancer:
  description:
    Detect if Gen1 Cloud Functions are not configured to allow only internal traffic and traffic from load balancer
  predicate:
    expression: (!resource.ingressSettings.matches("ALLOW_INTERNAL_AND_GCLB"))
  recommendation:
    Ensure Gen1 Cloud Functions are configured to allow only internal traffic and traffic from load balancer
  resource_selector:
    resource_types:
      - cloudfunctions.googleapis.com/CloudFunction
  severity: MEDIUM
