severity: HIGH
description: Detect if Gen1 Cloud Functions are not configured to allow only internal traffic
recommendation: Ensure Gen1 Cloud Functions are configured to allow only internal traffic
resource_selector:
  resource_types:
    - cloudfunctions.googleapis.com/CloudFunction
predicate:
  expression: (!resource.ingressSettings.matches("ALLOW_INTERNAL_ONLY"))
