processors:
  - scc

outputs:
  - type: mail
    transports:
      - type: smtp
        host: your.email.server.smtp
        port: 587
        ssl: true
    from: notifications@your.domain
    # For programmatic creation of recipient, see the budget example.
    to: security@your.domain
    subject: |
      [Security Center - {{ finding.sourceProperties.SeverityLevel }}] {{ finding.category }}: {{ finding.resourceName }}
    body:
      images: # Images to inline in the email
        - img/sample-logo-small.png
      html: |
        <html><head><title>Cloud Security Center notification</title></head>
        <body>
          <img src="cid:sample-logo-small.png" alt="Sample logo" />
          <h1>Cloud Security Center notification</h1>
          <p>The following finding was discovered:</p>
          <table>
            <tr>
              <th>Time</th>
              <td>{{ finding.createTime }}</td>
            </tr>
            <tr>
              <th>Finding name</th>
              <td>{{ finding.name|split('/')|index(-1) }}</td>
            </tr>
            <tr>
              <th>Resource</th>
              <td>{{ finding.resourceName }}</td>
            </tr>
            <tr>
              <th>Category</th>
              <td>{{ finding.category }}</td>
            </tr>
            <tr>
              <th>URL</th>
              <td><a href="{{ finding.externalUri }}">{{ finding.externalUri }}</a></td>
            </tr>
            <tr>
              <th>Recommendation</th>
              <td>{{ finding.sourceProperties.Recommendation|add_links }}</td>
            </tr>
            <tr>
              <th>Explanation</th>
              <td>{{ finding.sourceProperties.Explanation|add_links }}</td>
            </tr>
          </table>
          <p>
          <a href="https://console.cloud.google.com/security/command-center/findings?organizationId={{ organization }}&orgonly=true&supportedpurview=organizationId&view_type=vt_finding_type&vt_finding_type=All&resourceId={{ finding.name|urlencode }}">View in Security Command Center</a>
          </p>
        </body>
        </html>
      text: |
        *Cloud Security Center notification*

        The following finding was discovered:
        
        Time: {{ finding.createTime }}
        Finding name: {{ finding.name|split('/')|index(-1) }}
        Resource: {{ finding.resourceName }}
        Category: {{ finding.category }}
        URL: {{ finding.externalUri }}
        Recommendation: {{ finding.sourceProperties.Recommendation }}
        Explanation: {{ finding.sourceProperties.Explanation }}

        View in Security Command Center:
        https://console.cloud.google.com/security/command-center/findings?organizationId={{ organization }}&orgonly=true&supportedpurview=organizationId&view_type=vt_finding_type&vt_finding_type=All&resourceId={{ finding.name|urlencode }}
      
  