steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/helm:${_HELM_VERSION}', '--tag=gcr.io/$PROJECT_ID/helm:latest', '--build-arg', 'HELM_VERSION=v${_HELM_VERSION}', '.']
# Sanity Check: make sure basic functionality works
- name: 'gcr.io/$PROJECT_ID/helm:latest'
  args: ['version', '--client']
  env:
    - SKIP_CLUSTER_CONFIG=true
images:
  - 'gcr.io/$PROJECT_ID/helm:${_HELM_VERSION}'
  - 'gcr.io/$PROJECT_ID/helm:latest'
tags: ['cloud-builders-community']
substitutions:
  _HELM_VERSION: 3.12.0
