# Copyright 2021 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Download the Google Cloud SDK package repository signing key
  get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/cloud.google.gpg

- name: Add Google Cloud SDK package repository source
  apt_repository:
    filename: google-cloud-sdk.list
    repo: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    update_cache: yes

- name: Install dependencies
  apt:
    pkg:
      - kubectl
      - google-cloud-sdk-gke-gcloud-auth-plugin
      - jq
    state: present

- name: Install gke-gcloud-auth-plugin
  apt:
    name: google-cloud-sdk-gke-gcloud-auth-plugin
    state: present