apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: prod
  git:
    syncRepo: https://gitlab.com/<GROUP_URI>/acm-repo.git
    syncBranch: main
    secretType: none
  policyController:
    enabled: true
